name: Update dependencies with Gilt (Go)

on:
 
  repository_dispatch:
    types: 
      - trigger-workflow-from-repo1
      - trigger-workflow-from-repo2
      - trigger-workflow-from-repo3


  workflow_dispatch:



jobs:
  update-depdencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21.x' 

      - name: Install Gilt
        run: |
          go install github.com/retr0h/gilt/v2@latest
          export PATH=$PATH:$(go env GOPATH)/bin

      - name: Use Gilt to pull dependencies
        run: |
          gilt --debug overlay

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update dependencies with Gilt"
            git push origin main
          else
            echo "No changes to commit"
          fi
